### ISSUE TITLE
Name?

### ISSUE THREAD

**Issue by cjfields** [bioperl/Bio-Procedural#1]
We need to decide whether to stick with `Bio::Procedural` prior to CPAN submission.

**Comment by carandraug** [comment]
The module is still named `Bio::Perl` so you could name this distribution `Bio-Perl`. However, that will be pretty confusing because there's a BioPerl project and organization, a `BioPerl` distribution, a `BioPerl` module (documentation only), and a `Bio::Perl` module that provides a procedural interface to a subset of `Bio::`.  This would add a `Bio-Perl` distribution to the mix.

I named it Procedural (this is a procedural interface, not a functional interface like the docs says) because I needed something for the repo. Another suggestion, which would be common in this type of stuff, is something like `Bio-Simple`.

**Comment by cjfields** [comment]
Coming back to this based on the mail list discussion.  @carandraug I like `Bio-Simple`; if we have some agreement here we can rename the repo and get this on CPAN.

**Comment by carandraug** [comment]
Simple is among the [module names to avoid by PAUSE recommendations](https://pause.perl.org/pause/query?ACTION=pause_namingmodules#NAMES_TO_AVOID)

> The terms Simple, Easy, Reduced, and Tiny are some of the worst parts of the names on CPAN. They all indicate that the module is a variation of another module, but why is that variation interesting? It's usually missing or hiding some features, less flexible than the original, and in most cases, tailored to the task the author needed. What is that task though? Making it easy for you doesn't mean it's easy for the next programmer.

**Comment by cjfields** [comment]
Let's stick with `Bio::Procedural` then.
